SignText: "[v10lift]"
DefectText: "&kDefect!"
DisabledText: "&cDisabled"
MaintenanceText: "&cMaintenance"
DefectRate: 0.0
RepairItem: REDSTONE
RepairAmount: 5
MasterRepairItem: DIAMOND
MasterRepairAmount: 10
DefaultSpeed: 16
DefaultRealistic: true
DoorCloseTime: 100
CheckUpdates: true