name: V10Lift
main: tech.sbdevelopment.v10lift.V10LiftPlugin
version: ${project.version}
api-version: "1.13"
author: SBDeveloper
softdepend: ["Vault"]
commands:
  v10lift:
    description: The V10Lift Command
permissions:
  v10lift.admin:
    description: The full power admin permission
    default: op
  v10lift.build:
    description: The permission to build a lift
  v10lift.reload:
    description: Reload the plugin
  v10lift.repair:
    description: Repair a lift
  v10lift.disable:
    description: Disable a lift
  v10lift.start:
    description: Start a lift
  v10lift.stop:
    description: Stop a lift
  v10lift.list:
    description: List all lifts
  v10lift.setoffline:
    description: Set a lift offline / online